/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VerFotos.java
 *
 * Created on 11/08/2009, 17:40:33
 */

package nivers;

import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author 8741417
 */
public class FrVerFotos extends javax.swing.JFrame {

    /** Creates new form VerFotos */
    public FrVerFotos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLInicio = new javax.swing.JLabel();
        jFTFDataNiver = new javax.swing.JFormattedTextField();
        jComboBoxData = new comp.CalendarComboBox();
        jLFim = new javax.swing.JLabel();
        jFTFDataNiver2 = new javax.swing.JFormattedTextField();
        jComboBoxData2 = new comp.CalendarComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTFDias = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jBOk = new javax.swing.JButton();
        jBCancel = new javax.swing.JButton();
        JButton[]botoes=new JButton[200];
        jBFoto1 = new JButton();
        jLFoto1 = new javax.swing.JLabel();
        jBFoto2 = new javax.swing.JButton();
        jBFoto3 = new javax.swing.JButton();
        jBFoto4 = new javax.swing.JButton();
        jBFoto5 = new javax.swing.JButton();
        jBFoto6 = new javax.swing.JButton();
        jBFoto7 = new javax.swing.JButton();
        jBFoto8 = new javax.swing.JButton();
        jLFoto2 = new javax.swing.JLabel();
        jLFoto3 = new javax.swing.JLabel();
        jLFoto4 = new javax.swing.JLabel();
        jLFoto5 = new javax.swing.JLabel();
        jLFoto6 = new javax.swing.JLabel();
        jLFoto7 = new javax.swing.JLabel();
        jLFoto8 = new javax.swing.JLabel();
        jBFoto9 = new javax.swing.JButton();
        jBFoto10 = new javax.swing.JButton();
        jBFoto11 = new javax.swing.JButton();
        jBFoto12 = new javax.swing.JButton();
        jBFoto13 = new javax.swing.JButton();
        jBFoto14 = new javax.swing.JButton();
        jBFoto15 = new javax.swing.JButton();
        jBFoto16 = new javax.swing.JButton();
        jLFoto9 = new javax.swing.JLabel();
        jLFoto10 = new javax.swing.JLabel();
        jLFoto11 = new javax.swing.JLabel();
        jLFoto12 = new javax.swing.JLabel();
        jLFoto13 = new javax.swing.JLabel();
        jLFoto14 = new javax.swing.JLabel();
        jLFoto15 = new javax.swing.JLabel();
        jLFoto16 = new javax.swing.JLabel();
        jBFoto17 = new javax.swing.JButton();
        jLFoto17 = new javax.swing.JLabel();
        jBFoto18 = new javax.swing.JButton();
        jBFoto19 = new javax.swing.JButton();
        jBFoto20 = new javax.swing.JButton();
        jBFoto21 = new javax.swing.JButton();
        jBFoto22 = new javax.swing.JButton();
        jBFoto23 = new javax.swing.JButton();
        jBFoto24 = new javax.swing.JButton();
        jLFoto18 = new javax.swing.JLabel();
        jLFoto19 = new javax.swing.JLabel();
        jLFoto20 = new javax.swing.JLabel();
        jLFoto21 = new javax.swing.JLabel();
        jLFoto22 = new javax.swing.JLabel();
        jLFoto23 = new javax.swing.JLabel();
        jLFoto24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pesquisar aniversariantes por intervalo de dias");

        jLInicio.setText("Data de início");

        jComboBoxData.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxData.setFocusable(false);
        jComboBoxData.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDataItemStateChanged(evt);
            }
        });

        jLFim.setText("Data final");

        jComboBoxData2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxData2.setFocusable(false);
        jComboBoxData2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxData2ItemStateChanged(evt);
            }
        });

        jLabel2.setText("Digite a quantidade de dias para frente");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 8));
        jLabel4.setText("(Somente números)");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pesquisar próximos aniversariantes");

        jBOk.setText("Pesquisar");
        jBOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOkActionPerformed(evt);
            }
        });

        jBCancel.setText("Voltar");
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });

        jLFoto1.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLFoto1.setText("Nome");
        jLFoto1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jBFoto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFoto2ActionPerformed(evt);
            }
        });

        jLFoto2.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLFoto2.setText("Nome");
        jLFoto2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLFoto3.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLFoto3.setText("Nome");
        jLFoto3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLFoto4.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLFoto4.setText("Nome");
        jLFoto4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLFoto5.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLFoto5.setText("Nome");
        jLFoto5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLFoto6.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLFoto6.setText("Nome");
        jLFoto6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLFoto7.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLFoto7.setText("Nome");
        jLFoto7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLFoto8.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLFoto8.setText("Nome");
        jLFoto8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLFoto9.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLFoto9.setText("Nome");
        jLFoto9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLFoto10.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLFoto10.setText("Nome");
        jLFoto10.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLFoto11.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLFoto11.setText("Nome");
        jLFoto11.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLFoto12.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLFoto12.setText("Nome");
        jLFoto12.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLFoto13.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLFoto13.setText("Nome");
        jLFoto13.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLFoto14.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLFoto14.setText("Nome");
        jLFoto14.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLFoto15.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLFoto15.setText("Nome");
        jLFoto15.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLFoto16.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLFoto16.setText("Nome");
        jLFoto16.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLFoto17.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLFoto17.setText("Nome");
        jLFoto17.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLFoto18.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLFoto18.setText("Nome");
        jLFoto18.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLFoto19.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLFoto19.setText("Nome");
        jLFoto19.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLFoto20.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLFoto20.setText("Nome");
        jLFoto20.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLFoto21.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLFoto21.setText("Nome");
        jLFoto21.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLFoto22.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLFoto22.setText("Nome");
        jLFoto22.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLFoto23.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLFoto23.setText("Nome");
        jLFoto23.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLFoto24.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLFoto24.setText("Nome");
        jLFoto24.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBCancel))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLInicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTFDataNiver, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxData, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jLFim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFTFDataNiver2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxData2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFDias, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFoto4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFoto5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFoto6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFoto7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFoto8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLFoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLFoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLFoto4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLFoto5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLFoto6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLFoto7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLFoto8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBFoto9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFoto10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFoto11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFoto12, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFoto13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFoto14, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFoto15, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFoto16, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLFoto9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLFoto10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLFoto11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLFoto12, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLFoto13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLFoto14, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLFoto15, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLFoto16, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBFoto17, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFoto18, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFoto19, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFoto20, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFoto21, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFoto22, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFoto23, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFoto24, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLFoto17, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLFoto18, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLFoto19, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLFoto20, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLFoto21, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLFoto22, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLFoto23, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLFoto24, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLFoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLFoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLFoto4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLFoto5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLFoto6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLFoto7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLFoto8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jBFoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFoto4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFoto5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFoto6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFoto7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFoto8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBFoto15, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFoto14, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFoto13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFoto12, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFoto11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFoto10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFoto9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFoto16, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFoto9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFoto10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFoto11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFoto12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFoto13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFoto14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFoto15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFoto16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBFoto17, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLFoto17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLFoto18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLFoto19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLFoto20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLFoto21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLFoto22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLFoto23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLFoto24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jBFoto18, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFoto19, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFoto20, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFoto21, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFoto22, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFoto23, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFoto24, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFTFDataNiver2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxData2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFTFDataNiver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLInicio)
                        .addComponent(jLFim)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancel)
                    .addComponent(jBOk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxDataItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDataItemStateChanged
        jFTFDataNiver.setText(String.valueOf(jComboBoxData.getSelectedItem().toString()));
        String dataini = jFTFDataNiver.getText();
        dataini = conectar.converterData_pt_en(dataini);
        dataini = CalcDatas.soma_data_dia(dataini, 1);
        dataini = conectar.converterData_en_pt(dataini);
        //        JOptionPane.showMessageDialog(null, dataini);
        if (jFTFDataNiver2.getText().equals("")){
            //jFTFDataNiver2.setText(String.valueOf(jComboBoxData.getSelectedItem().toString()));
            jComboBoxData2.receberData(dataini);
            jFTFDataNiver2.setText(dataini);
        }
}//GEN-LAST:event_jComboBoxDataItemStateChanged

    private void jComboBoxData2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxData2ItemStateChanged
        jFTFDataNiver2.setText(String.valueOf(jComboBoxData2.getSelectedItem().toString()));
}//GEN-LAST:event_jComboBoxData2ItemStateChanged

    private void jBOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOkActionPerformed
        JButton[]botoes=new JButton[200];


        /*        for(int i=0;i<200;i++) botoes[i]=new ...

        String paux = new String();
        paux = "2";
        for (int i=1; i<25;i++){
            ImageIcon icon = new ImageIcon("\\\\\\\\srvpdc\\\\fotos\\\\"+paux+".jpg");
            jBFoto1.setIcon(icon);
            jBFoto+String.valueOf(i).setIcon(icon);

            criar um array de botões e um array de labels

            SE FOR PRECISO, CRIAR FRAME NA "MÃO".
        }
/*
        if (!(jFTFDataNiver2.getText().toString().equals("")) && !(jFTFDataNiver.getText().toString().equals("")))
            intervalo_nivers();
        else if (!(jTFDias.getText().toString().equals("")))
            prox_nivers();
  */
}//GEN-LAST:event_jBOkActionPerformed

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        this.setVisible(false);
        nivers.ni.setVisible(true);
        //        System.exit(0);
}//GEN-LAST:event_jBCancelActionPerformed

    private void jBFoto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFoto2ActionPerformed
        // TODO add your handling code here:
        String paux = new String();
        paux = "2";
        ImageIcon icon = new ImageIcon("\\\\\\\\srvpdc\\\\fotos\\\\"+paux+".jpg");
        jBFoto2.setIcon(icon);

    }//GEN-LAST:event_jBFoto2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrVerFotos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBFoto1;
    private javax.swing.JButton jBFoto10;
    private javax.swing.JButton jBFoto11;
    private javax.swing.JButton jBFoto12;
    private javax.swing.JButton jBFoto13;
    private javax.swing.JButton jBFoto14;
    private javax.swing.JButton jBFoto15;
    private javax.swing.JButton jBFoto16;
    private javax.swing.JButton jBFoto17;
    private javax.swing.JButton jBFoto18;
    private javax.swing.JButton jBFoto19;
    private javax.swing.JButton jBFoto2;
    private javax.swing.JButton jBFoto20;
    private javax.swing.JButton jBFoto21;
    private javax.swing.JButton jBFoto22;
    private javax.swing.JButton jBFoto23;
    private javax.swing.JButton jBFoto24;
    private javax.swing.JButton jBFoto3;
    private javax.swing.JButton jBFoto4;
    private javax.swing.JButton jBFoto5;
    private javax.swing.JButton jBFoto6;
    private javax.swing.JButton jBFoto7;
    private javax.swing.JButton jBFoto8;
    private javax.swing.JButton jBFoto9;
    private javax.swing.JButton jBOk;
    private comp.CalendarComboBox jComboBoxData;
    private comp.CalendarComboBox jComboBoxData2;
    private javax.swing.JFormattedTextField jFTFDataNiver;
    private javax.swing.JFormattedTextField jFTFDataNiver2;
    private javax.swing.JLabel jLFim;
    private javax.swing.JLabel jLFoto1;
    private javax.swing.JLabel jLFoto10;
    private javax.swing.JLabel jLFoto11;
    private javax.swing.JLabel jLFoto12;
    private javax.swing.JLabel jLFoto13;
    private javax.swing.JLabel jLFoto14;
    private javax.swing.JLabel jLFoto15;
    private javax.swing.JLabel jLFoto16;
    private javax.swing.JLabel jLFoto17;
    private javax.swing.JLabel jLFoto18;
    private javax.swing.JLabel jLFoto19;
    private javax.swing.JLabel jLFoto2;
    private javax.swing.JLabel jLFoto20;
    private javax.swing.JLabel jLFoto21;
    private javax.swing.JLabel jLFoto22;
    private javax.swing.JLabel jLFoto23;
    private javax.swing.JLabel jLFoto24;
    private javax.swing.JLabel jLFoto3;
    private javax.swing.JLabel jLFoto4;
    private javax.swing.JLabel jLFoto5;
    private javax.swing.JLabel jLFoto6;
    private javax.swing.JLabel jLFoto7;
    private javax.swing.JLabel jLFoto8;
    private javax.swing.JLabel jLFoto9;
    private javax.swing.JLabel jLInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTFDias;
    // End of variables declaration//GEN-END:variables

}
