/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Intervalo.java
 *
 * Created on 16/06/2009, 11:21:26
 */

package nivers;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author 8741417
 */
public class Intervalo extends javax.swing.JFrame {

    /** Creates new form Intervalo */
    public Intervalo() {
        initComponents();
        setLocationRelativeTo(null); //CENTRALIZANDO PAINEL
    }
    private JPanel registros;
    private nivers ni_aux = new nivers();

    public void intervalo_nivers(){

            String data_hoje = new String();
            String data_hoje2 = new String();
            String data_lim = new String();
            String data_lim2 = new String();

            data_hoje = String.valueOf(jFTFDataNiver.getText()); // dd-MM-yyyy
            data_hoje = conectar.converterData_pt_en(data_hoje); // yyyy-MM-dd

            data_lim = String.valueOf(jFTFDataNiver2.getText()); // dd-MM-yyyy
            data_lim = conectar.converterData_pt_en(data_lim); // yyyy-MM-dd

            data_hoje = data_hoje.substring(5, 10); // MM-dd
            data_lim = data_lim.substring(5, 10);   // MM-dd

            String mes_hj = new String();
            String dia_hj = new String();
            String mes_lim  = new String();
            String dia_lim = new String();

            mes_hj = data_hoje.substring(0,2);
            dia_hj = data_hoje.substring(3,5);
            mes_lim = data_lim.substring(0,2);
            dia_lim = data_lim.substring(3,5);

            int i_mes_hj = Integer.parseInt(mes_hj);
            int i_dia_hj = Integer.parseInt(dia_hj);
            int i_mes_lim = Integer.parseInt(mes_lim);
            int i_dia_lim = Integer.parseInt(dia_lim);

//            JOptionPane.showMessageDialog(null, "mes_hj = "+ String.valueOf(i_mes_hj) +"\ndia_hj = "+ String.valueOf(i_dia_hj)+"\nmes_lim = " +String.valueOf(i_mes_lim)+"\ndia_lim = "+ String.valueOf(i_dia_lim) );
          String qr = "WHERE (DATE_FORMAT( niver, '%m-%d' ) BETWEEN '"+data_hoje+"' AND '"+data_lim+"' ) ";
          /*verificação se virou o ano ou não*/
          if (((i_mes_hj == i_mes_lim) && (i_dia_hj >= i_dia_lim)) || (i_mes_hj > i_mes_lim)){
                data_lim2 = "12-31";
                data_hoje2 = "01-01";
                qr = "WHERE (DATE_FORMAT( niver, '%m-%d' ) BETWEEN '"+data_hoje+"' AND '"+data_lim2+"') OR (DATE_FORMAT( niver, '%m-%d' ) BETWEEN '"+data_hoje2+"' AND '"+data_lim+"')";
            }

            nivers.spu = "";
            registros = null;
            registros = new p_interv_nivers(qr);
            JOptionPane.showMessageDialog(this, this.registros, "..:: Selecione um registro ::..", JOptionPane.PLAIN_MESSAGE);
//            JOptionPane.showMessageDialog(null, nivers.spu);
            if ((nivers.spu != null) && !(nivers.spu.equals("")))
                nivers.ni.selecionar(nivers.spu);
            this.setVisible(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLInicio = new javax.swing.JLabel();
        jLFim = new javax.swing.JLabel();
        jFTFDataNiver = new javax.swing.JFormattedTextField();
        jFTFDataNiver2 = new javax.swing.JFormattedTextField();
        jComboBoxData = new comp.CalendarComboBox();
        jComboBoxData2 = new comp.CalendarComboBox();
        jBOk = new javax.swing.JButton();
        jBCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("..:: Listar Aniversariantes em intervalo ::..");

        jLInicio.setText("Data de início");

        jLFim.setText("Data final");

        jComboBoxData.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxData.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDataItemStateChanged(evt);
            }
        });

        jComboBoxData2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxData2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxData2ItemStateChanged(evt);
            }
        });

        jBOk.setText("OK");
        jBOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOkActionPerformed(evt);
            }
        });

        jBCancel.setText("Cancelar");
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLInicio)
                    .addComponent(jFTFDataNiver, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxData, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLFim)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBOk)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBCancel))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jFTFDataNiver2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBoxData2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLInicio)
                    .addComponent(jLFim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTFDataNiver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTFDataNiver2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxData2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancel)
                    .addComponent(jBOk))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxDataItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDataItemStateChanged
        jFTFDataNiver.setText(String.valueOf(jComboBoxData.getSelectedItem().toString()));
        String dataini = jFTFDataNiver.getText();
        dataini = conectar.converterData_pt_en(dataini);
        dataini = CalcDatas.soma_data_dia(dataini, 1);
        dataini = conectar.converterData_en_pt(dataini);
//        JOptionPane.showMessageDialog(null, dataini);
        if (jFTFDataNiver2.getText().equals("")){
            //jFTFDataNiver2.setText(String.valueOf(jComboBoxData.getSelectedItem().toString()));
            jComboBoxData2.receberData(dataini);
            jFTFDataNiver2.setText(dataini);
        }
}//GEN-LAST:event_jComboBoxDataItemStateChanged

    private void jComboBoxData2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxData2ItemStateChanged
        jFTFDataNiver2.setText(String.valueOf(jComboBoxData2.getSelectedItem().toString()));
}//GEN-LAST:event_jComboBoxData2ItemStateChanged

    private void jBOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOkActionPerformed
        if (!(jFTFDataNiver2.getText().toString().equals("")) && !(jFTFDataNiver.getText().toString().equals("")))
        {
            this.setVisible(false);
            this.intervalo_nivers();
            nivers.ni.setVisible(true);
        }
        else
            this.setVisible(false);
    }//GEN-LAST:event_jBOkActionPerformed

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jBCancelActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Intervalo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBOk;
    private comp.CalendarComboBox jComboBoxData;
    private comp.CalendarComboBox jComboBoxData2;
    private javax.swing.JFormattedTextField jFTFDataNiver;
    private javax.swing.JFormattedTextField jFTFDataNiver2;
    private javax.swing.JLabel jLFim;
    private javax.swing.JLabel jLInicio;
    // End of variables declaration//GEN-END:variables

}
