/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * P_Intervalo.java
 *
 * Created on 16/06/2009, 11:28:12
 */

package nivers;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author 8741417
 */
public class P_Intervalo extends javax.swing.JPanel {
    /** Creates new form P_Intervalo */
    public P_Intervalo() {
        this.setVisible(true);
        initComponents();
//        setLocationRelativeTo(null); //CENTRALIZANDO PAINEL
    }
    private JPanel registros;
    private nivers ni_aux = new nivers();

    public void intervalo_nivers(){

            String data_hoje = new String();
            String data_hoje2 = new String();
            String data_lim = new String();
            String data_lim2 = new String();

            data_hoje = String.valueOf(jFTFDataNiver.getText()); // dd-MM-yyyy
            data_hoje = conectar.converterData_pt_en(data_hoje); // yyyy-MM-dd

            data_lim = String.valueOf(jFTFDataNiver2.getText()); // dd-MM-yyyy
            data_lim = conectar.converterData_pt_en(data_lim); // yyyy-MM-dd

            data_hoje = data_hoje.substring(5, 10); // MM-dd
            data_lim = data_lim.substring(5, 10);   // MM-dd

            String mes_hj = new String();
            String dia_hj = new String();
            String mes_lim  = new String();
            String dia_lim = new String();

            mes_hj = data_hoje.substring(0,2);
            dia_hj = data_hoje.substring(3,5);
            mes_lim = data_lim.substring(0,2);
            dia_lim = data_lim.substring(3,5);

            int i_mes_hj = Integer.parseInt(mes_hj);
            int i_dia_hj = Integer.parseInt(dia_hj);
            int i_mes_lim = Integer.parseInt(mes_lim);
            int i_dia_lim = Integer.parseInt(dia_lim);

//            JOptionPane.showMessageDialog(null, "mes_hj = "+ String.valueOf(i_mes_hj) +"\ndia_hj = "+ String.valueOf(i_dia_hj)+"\nmes_lim = " +String.valueOf(i_mes_lim)+"\ndia_lim = "+ String.valueOf(i_dia_lim) );
          String qr = "WHERE (DATE_FORMAT( niver, '%m-%d' ) BETWEEN '"+data_hoje+"' AND '"+data_lim+"' ) ";
          /*verificação se virou o ano ou não*/
          if (((i_mes_hj == i_mes_lim) && (i_dia_hj >= i_dia_lim)) || (i_mes_hj > i_mes_lim)){
                data_lim2 = "12-31";
                data_hoje2 = "01-01";
                qr = "WHERE (DATE_FORMAT( niver, '%m-%d' ) BETWEEN '"+data_hoje+"' AND '"+data_lim2+"') OR (DATE_FORMAT( niver, '%m-%d' ) BETWEEN '"+data_hoje2+"' AND '"+data_lim+"')";
            }

            nivers.spu = "";
            registros = null;
            registros = new p_prox_nivers(qr);
            JOptionPane.showMessageDialog(this, this.registros, "..:: Selecione um registro ::..", JOptionPane.PLAIN_MESSAGE);
            if ((nivers.spu != null) && !(nivers.spu.equals(""))) {
                String sel[] = null;
                sel = new String[13];
                String spu_aux = "WHERE nome = \'" + nivers.spu + "\'";
/* bolar uma forma para selecionar no frame nivers os campos do cadastro selecionaro */
                /*
                sel = ni_aux.ret_selecionado(spu_aux);
                
                jTFCodPessoa.setText(sel[0]);
                jCBTipo.setSelectedIndex((Integer.parseInt(sel[1])) - 1);
                jCBPronome.setSelectedIndex((Integer.parseInt(sel[2])) - 1);
                jTFNome.setText(sel[3]);
                jTFCargo.setText(sel[4]);
                sel[5] = conectar.converterData_en_pt(sel[5]);
                getJFTFDataNiver().setText(sel[5]);
                getJComboBoxData().receberData(sel[5]);
                jTFFone.setText(sel[6]);
                jTFEmail.setText(sel[7]);
                if (sel[8].equals("1")) {
                    jRBMasc.isSelected();
                } else {
                    jRBFem.isSelected();
                }

                jTFDias.setText(sel[10]);
                if ((sel[12].equals("null")) || (sel[12].equals(""))) {
                    jTAObs.setText(null);
                } else {
                    jTAObs.setText(sel[12]);
                }
                */
            }

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLInicio = new javax.swing.JLabel();
        jFTFDataNiver = new javax.swing.JFormattedTextField();
        jComboBoxData = new comp.CalendarComboBox();
        jFTFDataNiver2 = new javax.swing.JFormattedTextField();
        jComboBoxData2 = new comp.CalendarComboBox();
        jLFim = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBOk = new javax.swing.JButton();
        jBCancel = new javax.swing.JButton();

        jLInicio.setText("Data de início");

        jComboBoxData.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxData.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDataItemStateChanged(evt);
            }
        });

        jComboBoxData2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxData2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxData2ItemStateChanged(evt);
            }
        });

        jLFim.setText("Data final");

        jLabel1.setFont(new java.awt.Font("Alaska", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("Pesquisar aniversariantes no intervalo");

        jBOk.setText("OK");
        jBOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOkActionPerformed(evt);
            }
        });

        jBCancel.setText("Cancelar");
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFTFDataNiver, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxData, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLInicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLFim)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBOk)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBCancel))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jFTFDataNiver2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBoxData2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFim)
                    .addComponent(jLInicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTFDataNiver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTFDataNiver2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxData2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancel)
                    .addComponent(jBOk))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxDataItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDataItemStateChanged
        getJFTFDataNiver().setText(String.valueOf(getJComboBoxData().getSelectedItem().toString()));
}//GEN-LAST:event_jComboBoxDataItemStateChanged

    private void jComboBoxData2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxData2ItemStateChanged
        getJFTFDataNiver2().setText(String.valueOf(getJComboBoxData2().getSelectedItem().toString()));
}//GEN-LAST:event_jComboBoxData2ItemStateChanged

    private void jBOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOkActionPerformed
        this.intervalo_nivers();
        this.setVisible(false);
        nivers.ni.setVisible(true);
        
    }//GEN-LAST:event_jBOkActionPerformed

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jBCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBOk;
    private comp.CalendarComboBox jComboBoxData;
    private comp.CalendarComboBox jComboBoxData2;
    private javax.swing.JFormattedTextField jFTFDataNiver;
    private javax.swing.JFormattedTextField jFTFDataNiver2;
    private javax.swing.JLabel jLFim;
    private javax.swing.JLabel jLInicio;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jComboBoxData
     */
    public comp.CalendarComboBox getJComboBoxData() {
        return jComboBoxData;
    }

    /**
     * @param jComboBoxData the jComboBoxData to set
     */
    public void setJComboBoxData(comp.CalendarComboBox jComboBoxData) {
        this.jComboBoxData = jComboBoxData;
    }

    /**
     * @return the jComboBoxData2
     */
    public comp.CalendarComboBox getJComboBoxData2() {
        return jComboBoxData2;
    }

    /**
     * @param jComboBoxData2 the jComboBoxData2 to set
     */
    public void setJComboBoxData2(comp.CalendarComboBox jComboBoxData2) {
        this.jComboBoxData2 = jComboBoxData2;
    }

    /**
     * @return the jFTFDataNiver
     */
    public javax.swing.JFormattedTextField getJFTFDataNiver() {
        return jFTFDataNiver;
    }

    /**
     * @param jFTFDataNiver the jFTFDataNiver to set
     */
    public void setJFTFDataNiver(javax.swing.JFormattedTextField jFTFDataNiver) {
        this.jFTFDataNiver = jFTFDataNiver;
    }

    /**
     * @return the jFTFDataNiver2
     */
    public javax.swing.JFormattedTextField getJFTFDataNiver2() {
        return jFTFDataNiver2;
    }

    /**
     * @param jFTFDataNiver2 the jFTFDataNiver2 to set
     */
    public void setJFTFDataNiver2(javax.swing.JFormattedTextField jFTFDataNiver2) {
        this.jFTFDataNiver2 = jFTFDataNiver2;
    }

}
