/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PronomeDeTratamento.java
 *
 * Created on 04/02/2009, 09:18:55
 */

package nivers;

/**
 *
 * @author 8741417
 */
public class PronomeDeTratamento extends javax.swing.JPanel {

    /** Creates new form PronomeDeTratamento */
    public PronomeDeTratamento() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTPMonarquicas = new javax.swing.JTabbedPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jTPCivis = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPOutros = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPJudiciaria = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPMilitares = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jPEclesiasticas = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jPMonarquicas = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jTextArea6.setText("Vossa Majestade Real & Imperial (V. M. R. & I.) Usado para: Monarcas que detenham títulos de imperador e rei ao mesmo tempo.\nVossa Majestade Imperial (V. M. I.) Usado para: Imperadores.\nVossa Majestade (V. M.) Usado para: Reis.\nVossa Alteza Real & Imperial (V. A. R. & I.) Usado para: Príncipes de casas reais e imperiais.\nVossa Alteza Imperial (V. A. I.) Usado para: Príncipes de casas imperiais.\nVossa Alteza Real (V. A. R.) Usado para: Príncipes e infantes de casas reais.\nVossa Alteza Sereníssima (V. A. S.) Usado para: Príncipes monarcas e Arquiduques.\nVossa Alteza (V. A.) Usado para: Duques.\nVossa Excelência (V. Exª.) Usado para: Duques com Grandeza, na Espanha.\nVossa Graça (V. G.) Usado para: Duques e Condes.\nVossa Alteza Ilustríssima (V. A. Ilmª.) Usado para: Nobres mediatizados, como Condes, na Alemanha.\nO Mui Honorável (M. Hon) Usado para: Marqueses, na Grã-Bretanha.\nO Honorável (Hon.) Usado para: Condes (The Right Hon.), Viscondes, Barões e filhos de Duques, Marqueses e Condes na Grã-Bretanha.\n");
        jScrollPane6.setViewportView(jTextArea6);

        jTPMonarquicas.addTab("tab1", jScrollPane6);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Você' (V.) usados para:familiares e amigos\nVossa Excelência' (V. Exª.) Usado para: presidente da República, senadores da República, ministros de Estado, governadores, deputados federais e estaduais, prefeitos, embaixadores, presidente de câmara de vereadores, cônsules, chefes das Casas Civis e Militares.\nVossa Magnificência (V. M.) Usado para: reitores de Universidade, pró-reitores e vice-reitores.\nVossa Senhoria (V. Sª.) Usado para: diretores de autarquias federais, estaduais e municipais.");
        jScrollPane1.setViewportView(jTextArea1);

        jTPCivis.addTab("Civis", jScrollPane1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Senhor (Sr.) Usado para: Homem, rapaz.\nSenhora (Sr.ª) Usado para: Mulher mais velha ou casada.\nSenhorita (Srt.ª) Usado para: Menina, moça solteira.\nVossa Senhoria (V. S.ª) Usado para: Pessoas importantes , como autoridades de uma cidade, como prefeito, algum secretário da prefeitura.\nIlustríssimo (Ilmo.) Usado para pessoas comuns, no mesmo sentido de Senhoria, delegados, diretores de alguma autarquia\nDoutor (Dr.) Usado para: Médico. Mas vale lembrar que este modo é usado erroneamente, pois doutor deve ser empregado a quem possui doutorado\nComendador (Com.) Usado para: Comendador.\nProfessor (Prof.) Usado para: Professor.\nPadre (Pe.) Usado para padres.\nPastor (Pr.) Usado para pastores de igrejas evangélicas.\n");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPOutrosLayout = new javax.swing.GroupLayout(jPOutros);
        jPOutros.setLayout(jPOutrosLayout);
        jPOutrosLayout.setHorizontalGroup(
            jPOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
        jPOutrosLayout.setVerticalGroup(
            jPOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );

        jTPCivis.addTab("Outros", jPOutros);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("Vossa Excelência (V. Exª) Usado Para: desembargadores de Justiça, ministros, procuradores, promotores.\nMeritíssimo Juiz (M. Juiz) Usado para: juízes de Direito.");
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPJudiciariaLayout = new javax.swing.GroupLayout(jPJudiciaria);
        jPJudiciaria.setLayout(jPJudiciariaLayout);
        jPJudiciariaLayout.setHorizontalGroup(
            jPJudiciariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
        jPJudiciariaLayout.setVerticalGroup(
            jPJudiciariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );

        jTPCivis.addTab("Judiciária", jPJudiciaria);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setText("Vossa Excelência (V. Exª.) Usado para: Oficias Generais (Almirantes-de-Esquadra, Generais-de-Exército e Tenentes-Brigadeiros; Vice-Almirantes, Generais-de-Divisão e Majores-Brigadeiros; Contra-Almirantes, Generais-de-Brigada e Brigadeiros) e Coronéis Comandantes das Forças Auxiliares dos Estados e DF (Polícias Militares e Bombeiros Militares).\nVossa Senhoria (V. Sª.) Usado para: Demais patentes e graduações militares.\n");
        jScrollPane4.setViewportView(jTextArea4);

        javax.swing.GroupLayout jPMilitaresLayout = new javax.swing.GroupLayout(jPMilitares);
        jPMilitares.setLayout(jPMilitaresLayout);
        jPMilitaresLayout.setHorizontalGroup(
            jPMilitaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
        jPMilitaresLayout.setVerticalGroup(
            jPMilitaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );

        jTPCivis.addTab("Militares", jPMilitares);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jTextArea5.setText("Vossa Santidade ( V. S.) Usado para: o Papa.\nVossa Eminência (V. Em.ª) Usado para: cardeais.\nVossa Excelência Reverendíssima (V. Ex.ª Revm.ª) Usado para: arcebispos e bispos.\nVossa Reverendíssima (V. Revmª) Usado para: abades, superiores de conventos, monsenhores, outras autoridades eclesiásticas e sacerdotes em geral.\n");
        jScrollPane5.setViewportView(jTextArea5);

        javax.swing.GroupLayout jPEclesiasticasLayout = new javax.swing.GroupLayout(jPEclesiasticas);
        jPEclesiasticas.setLayout(jPEclesiasticasLayout);
        jPEclesiasticasLayout.setHorizontalGroup(
            jPEclesiasticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
        jPEclesiasticasLayout.setVerticalGroup(
            jPEclesiasticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );

        jTPCivis.addTab("Eclesiásticas", jPEclesiasticas);

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jTextArea7.setText("Vossa Majestade Real & Imperial (V. M. R. & I.) Usado para: Monarcas que detenham títulos de imperador e rei ao mesmo tempo.\nVossa Majestade Imperial (V. M. I.) Usado para: Imperadores.\nVossa Majestade (V. M.) Usado para: Reis.\nVossa Alteza Real & Imperial (V. A. R. & I.) Usado para: Príncipes de casas reais e imperiais.\nVossa Alteza Imperial (V. A. I.) Usado para: Príncipes de casas imperiais.\nVossa Alteza Real (V. A. R.) Usado para: Príncipes e infantes de casas reais.\nVossa Alteza Sereníssima (V. A. S.) Usado para: Príncipes monarcas e Arquiduques.\nVossa Alteza (V. A.) Usado para: Duques.\nVossa Excelência (V. Exª.) Usado para: Duques com Grandeza, na Espanha.\nVossa Graça (V. G.) Usado para: Duques e Condes.\nVossa Alteza Ilustríssima (V. A. Ilmª.) Usado para: Nobres mediatizados, como Condes, na Alemanha.\nO Mui Honorável (M. Hon) Usado para: Marqueses, na Grã-Bretanha.\nO Honorável (Hon.) Usado para: Condes (The Right Hon.), Viscondes, Barões e filhos de Duques, Marqueses e Condes na Grã-Bretanha.\n");
        jScrollPane7.setViewportView(jTextArea7);

        javax.swing.GroupLayout jPMonarquicasLayout = new javax.swing.GroupLayout(jPMonarquicas);
        jPMonarquicas.setLayout(jPMonarquicasLayout);
        jPMonarquicasLayout.setHorizontalGroup(
            jPMonarquicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
        jPMonarquicasLayout.setVerticalGroup(
            jPMonarquicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );

        jTPCivis.addTab("Monárquicas", jPMonarquicas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPCivis, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPCivis, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPEclesiasticas;
    private javax.swing.JPanel jPJudiciaria;
    private javax.swing.JPanel jPMilitares;
    private javax.swing.JPanel jPMonarquicas;
    private javax.swing.JPanel jPOutros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTPCivis;
    private javax.swing.JTabbedPane jTPMonarquicas;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    // End of variables declaration//GEN-END:variables

}
